# Generated by Django 3.2.18 on 2023-05-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_discount_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='bluetooth',
            field=models.BooleanField(choices=[(False, '유선'), (True, '무선')], default=False, verbose_name='유/무선'),
        ),
        migrations.AlterField(
            model_name='category',
            name='tenkey',
            field=models.BooleanField(choices=[(False, '풀배열'), (True, '텐키리스')], default=False, verbose_name='배열'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_rate',
            field=models.IntegerField(),
        ),
    ]
